export const Ibuprofen = [
  {
    swissmedicIds: ['61220'],
    title: 'Amavita Ibuprofen 400',
    authHolder: 'Amavita Health Care AG',
    atcCode: 'M01AE01',
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['62695'],
    title: 'Coop Vitality Ibuprofen 200 mg/400 mg',
    authHolder: 'Coop Vitality Health Care GmbH',
    atcCode: 'M01AE01',
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['59162'],
    title: 'Ibuprofen N Helvepharm',
    authHolder: 'Helvepharm AG',
    atcCode: 'M01AE01',
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['48164'],
    title: 'Ibuprofen Sandoz®',
    authHolder: 'Sandoz Pharmaceuticals AG',
    atcCode: 'M01AE01',
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['62299'],
    title: 'Ibuprofen Sandoz® Retard 800',
    authHolder: 'Sandoz Pharmaceuticals AG',
    atcCode: 'M01AE01',
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['61220'],
    title: 'Amavita Ibuprofen 400',
    authHolder: 'Amavita Health Care AG',
    atcCode: null,
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['62695'],
    title: 'Coop Vitality Ibuprofen',
    authHolder: 'Coop Vitality Health Care GmbH',
    atcCode: null,
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['59162'],
    title: 'Ibuprofen N Helvepharm',
    authHolder: 'Helvepharm AG',
    atcCode: null,
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['48164'],
    title: 'Ibuprofen Sandoz®',
    authHolder: 'Sandoz Pharmaceuticals AG',
    atcCode: null,
    substances: ['Ibuprofen'],
  },
  {
    swissmedicIds: ['62299'],
    title: 'Ibuprofen Sandoz® Retard 800',
    authHolder: 'Sandoz Pharmaceuticals AG',
    atcCode: null,
    substances: ['Ibuprofen'],
  },
];
